rooms:
  office_a:
    x: -3.5
    y: -3.0
    yaw: 1.57
  office_b:
    x: 4.0
    y: 3.0
    yaw: 1.57
  server_room:
    x: 1.5
    y: 1.5
    yaw: 1.57
  hallway:
    x: 0.0
    y: -2.5
    yaw: 1.57
  base:
    x: 0.0
    y: -4.5
    yaw: 1.57
