rooms:
  office_a:
    x: -4.0
    y: -2.0
    yaw: 1.57
  office_b:
    x: 4.5
    y: 3.0
    yaw: 1.57
  server_room:
    x: 1.3
    y: 2.0
    yaw: 1.57
  hallway:
    x: 0.0
    y: -2.0
    yaw: 1.57
  base:
    x: 0.0
    y: -6.5
    yaw: 1.57
